// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LigerShark.OpenFromPortal
{
    static class Vsix
    {
        public const string Id = "4156516b-f6e6-40f2-aecb-ff99cded5f8a";
        public const string Name = "Open From Azure Websites";
        public const string Description = @"Open any Azure hosted web application as a Website Project.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "LigerShark";
        public const string Tags = "azure, website";
    }
}
